### ISSUE TITLE
Format & Separator issues

### ISSUE THREAD

**Issue by MarianArlt** [MarianArlt/kde-plasmoid-chiliclock#4]
@MarianArlt today I tried the updated version and it has a major bug so I will continue using my version.

It is called inline clock but it splits to two rows now:
![Screenshot_20190510_064407](https://user-images.githubusercontent.com/4855611/57503205-7a881680-72ef-11e9-8d9a-d38b5ad39dab.png)

Here is a screenshot of my config:
![Screenshot_20190510_064755](https://user-images.githubusercontent.com/4855611/57503330-faae7c00-72ef-11e9-8e07-424e30097938.png)

_The separator by the way is not working_

_Originally posted by @tflori in https://github.com/MarianArlt/kde-plasmoid-inlineclock/pull/2#issuecomment-491155063_

**Comment by MarianArlt** [comment]
@tflori thank you very much for reporting this. I failed on this one, it's clear that the first screenshot is on-desktop so it would adopt the usual behavior of the kde clock when sufficient space is available. This could be seen as a default feature or as unexpected behavior because of the name of the widget. I need to make a decision here between not allowing to stack at all under any circumstances or maybe rename the widget.

When you say the separator is not working, would you mind to elaborate? It does not show at all and you're not able to display it with the checkbox either?

**Comment by marlock9** [comment]
@MarianArlt Hello! I have the same issue.
![image](https://user-images.githubusercontent.com/9781492/59147381-5a896700-8a03-11e9-81cb-515b186fe18c.png)
Very frustrating because I specially install "inline" plasmoid to get away from plasma default widget behaviour where date is on new line.

**Comment by tflori** [comment]
@marianarlt no, it's on a latte dock.

**Comment by MarianArlt** [comment]
Ah sorry guys, will make an update soon.

**Comment by MarianArlt** [comment]
@tflori @marlock9 
I'm happy to announce the major release of v2.0 with a massive overhaul of options and fixes for these issues. Try it out!
