### ISSUE TITLE
Sometimes the width is not enough

### ISSUE THREAD

**Issue by trmdi** [MarianArlt/kde-plasmoid-chiliclock#8]
Please see the screenshot, look at the "M" in "AM":

![image](https://user-images.githubusercontent.com/11857205/67791264-b71c1a00-faa9-11e9-91db-a2628e00589c.png)

Reload the applet fixes it. I guess the width is a fixed value which is calculated when the applet starts.

**Comment by qiaojunfeng** [comment]
Me too, I have the same issue.

**Comment by qiaojunfeng** [comment]
I found a way to fix this:
In my machine, the plasmoid is installed at `~/.local/share/plasma/plasmoids/org.kde.plasma.chiliclock/`
Change the file `~.local/share/plasma/plasmoids/org.kde.plasma.chiliclock/contents/ui/DigitalClock.qml` line 164 
```
width: !use24hFormat || use24hFormat === Qt.PartiallyChecked ? sizehelper.contentWidth - separator.paintedWidth : sizehelper.contentWidth
```
to
```
width: sizehelper.contentWidth
```
can temporarily fix this.

It seems that the width of the plasmoid is calculated for a time such as `1:48 PM` but not for `10:48 PM`, so if an hour has 2 digits then it will excede the width of the plasmoid.

I don't have experience in writing plasmoid so this is certainly not a good fix. Maybe it's better to add an option to manually assign the width of the plasmoid.
